import META from './meta.mjs';
import Validator from './validator.mjs';
import ModelError from './model-error.mjs';

import mongo from 'mongodb';

import assert from 'assert';
import util from 'util';


/** 

All detected errors should be reported by throwing an array of
ModelError objects.  

Errors are of two types:

  + *Local errors* depend only on the field values of the current data
    item.  Local errors are specified and checked using meta.mjs
    and validator.mjs and are not specified below.

  + *Global errors* depend on data items other than the current data
    item.  The comments for the code below document global errors.

Each ModelError must be specified with an error code (defined below)
and an error message which should be as specific as possible.  If the
error is associated with a particular field, then the internal name of
that field should be filled in to the ModelError object.  Note that if
an error message refers to the name of the field, it should do so
using the external name (`label`) of the field.

The codes for the ModelError include the following:

BAD_ACT:
  Action does not correspond to one of the model action routines.

BAD_FIELD:
  An object contains an unknown field name or a forbidden field.

BAD_FIELD_VALUE:
  The value of a field does not meet its specs.

BAD_ID:
  Object not found for specified ID.  Includes an error when some field 
  specifies an id for some other object, but there is no object having
  that ID.

DB:
  Database error

FORM_ERROR:
  Form is invalid.

MISSING_FIELD:
  The value of a required field is not specified.

*/

export default class Model {

  /** Set up properties from props as properties of this. */
  constructor(props) {
    Object.assign(this, props);
  }

  /** Return a new instance of Model set up to use database specified
   *  by dbUrl
   */
  static async make(dbUrl) {
    let client;
    try {
      //@TODO
      client = await mongo.connect(dbUrl, MONGO_CONNECT_OPTIONS);

      const db = client.db(DB_NAME);

      const props = {
        validator: new Validator(META),
        //@TODO other properties
        client: client,
        db: db
      };

      const shopping_cart = await db.collection(COLLECTIONS.SHOPPING_CART);
      shopping_cart.createIndex({ cartId: 1 });
      shopping_cart.createIndex({ sku: 1 });
      shopping_cart.createIndex({ nUnits: 1 });
      shopping_cart.createIndex({ _lastModified: 1 });

      props.shopping_cart = shopping_cart;

      const bookCatalog = await db.collection(COLLECTIONS.BOOK_CATALOG);
      bookCatalog.createIndex({ isbn: 1 });
      bookCatalog.createIndex({ title: 1 });
      bookCatalog.createIndex({ authors: 1 });
      bookCatalog.createIndex({ publisher: 1 });
      bookCatalog.createIndex({ year_published: 1 });
      bookCatalog.createIndex({ no_of_pages: 1 });
      bookCatalog.createIndex({ _lastModified: 1 });

      props.bookCatalog = bookCatalog;

      const model = new Model(props);

      // console.log('Model', model);

      return model;
    }
    catch (err) {
      const msg = `cannot connect to URL "${dbUrl}": ${err}`;
      throw [new ModelError('DB', msg)];
    }
  }

  /** Release all resources held by this model.  Specifically,
   *  close any database connections.
   */
  async close() {
    //@TODO
    try {
      await this.client.close();

    } catch (error) {
      const msg = `Error while closing database: ${error}`;
      throw [new ModelError('DB', msg)];
    }
  }

  /** Clear out all data stored within this model. */
  async clear() {
    //@TODO
    try {
      await this.db.collection(COLLECTIONS.SHOPPING_CART).drop();
      await this.db.collection(COLLECTIONS.BOOK_CATALOG).drop();
      this.db.dropDatabase();
      console.log('Database cleared');

    } catch (error) {
      const msg = `Error while closing database: ${error}`;
      throw [new ModelError('DB', msg)];
    }
  }

  //Action routines

  /** Create a new cart.  Returns ID of newly created cart.  The
   * returned ID should not be generated by the database; it should
   * also not be easily guessable.
   *
   *  The new cart should have a `_lastModified` field set to the
   *  current Date timestamp.
   */
  async newCart(rawNameValues) {
    try {
      const nameValues = this._validate('newCart', rawNameValues);
      // console.log('Name Value', nameValues);
      randomCounter++;
      // console.log('This DB', this.db);
      const shopping_cart = this.db.collection(COLLECTIONS.SHOPPING_CART);
      const _cart = {
        cartId: Math.random().toString() + randomCounter,
        _lastModified: new Date().toISOString()
      };

      const cartAdded = await shopping_cart.insertOne(_cart);
      console.log('Cart', _cart, cartAdded);
      if (cartAdded.insertedId === _cart._id) {
        console.log('New cart added.');
        return _cart.cartId;
      }
      return null;
    } catch (err) {
      const msg = `Error while closing database: ${err}`;
      throw [new ModelError('DB', msg)];

    }

  }

  /** Given fields { cartId, sku, nUnits } = rawNameValues, update
   *  number of units for sku to nUnits.  Update `_lastModified` field
   *  of cart to current Date timestamp.
   *
   *  Global Errors:
   *    BAD_ID: cartId does not reference a cart.
   *            sku does not specify the isbn of an existing book.
   */
  async cartItem(rawNameValues) {

    //@TODO

    try {
      const nameValues = this._validate('cartItem', rawNameValues);

      const cartTable = this.db.collection(COLLECTIONS.SHOPPING_CART);
      const cursor = await this.findBooks({ isbn: nameValues.sku });
      // console.log('SKU', cursor[0].isbn, nameValues.sku);
      if (cursor[0].isbn === nameValues.sku) {
        const matched = await cartTable.updateOne(
          {
            cartId: nameValues.cartId.toString()
          },
          {
            $set: {
              sku: nameValues.nUnits > 0 ? nameValues.sku : {},
              nUnits: nameValues.nUnits,
              _lastModified: new Date().toISOString()
            }
          }
        );

        console.log('Update', matched, matched.matchedCount);
        if (matchedCount != 1) {


          const msg = `BAD_ID`;
          throw [new ModelError('BAD_ID', msg)]
        } else {
          console.log('Updated');

        }
      } else {

        const msg = `unknown sku ${nameValues.sku}`;
        throw [new ModelError('BAD_ID', msg, 'sku')];
      }
    } catch (err) {

      const msg = `unknown sku ${err}`;
      throw [new ModelError('BAD_ID', msg, 'sku')];
    }


  }

  /** Given fields { cartId } = nameValues, return cart identified by
   *  cartId.  The cart is returned as an object which contains a
   *  mapping from SKU's to *positive* integers (representing the
   *  number of units of the item identified by the SKU contained in
   *  the cart).  Addtionally, it must also have a `_lastModified`
   *  property containing a Date timestamp specifying the last time the
   *  cart was modified.
   *
   *  Globals Errors:
   *    BAD_ID: cartId does not reference a cart.
   */
  async getCart(rawNameValues) {
    const nameValues = this._validate('getCart', rawNameValues);
    //@TODO
    try {
      const cartCursor = await this.db.collection(COLLECTIONS.SHOPPING_CART).findOne(
        {
          cartId: nameValues.cartId.toString(),
          nUnits: { $gt: 0 }
        });
      console.log('Cursor', cartCursor);

      if (cartCursor) {
        return { _lastModified: cartCursor._lastModified, [cartCursor.sku]: cartCursor.nUnits };
      } else {
        throw [new ModelError('DB', 'BAD_ID')];
      }
    } catch (err) {
      const msg = `${nameValues.cartId} does not reference a cart`
      throw [new ModelError('BAD_ID', msg)];
    }


  }

  /** Given fields { isbn, title, authors, publisher, year, pages } =
   *  nameValues for a book, add the book to this model.  The isbn
   *  field should uniquely identify the book.  Note that if the book
   *  already exists in this model, then this routine should merely
   *  update the information associated with the book.
   *
   *  Returns the isbn of the added/updated book.
   *
   *  This routine should set a `_lastModified` field in the book to
   *  the current Date timestamp.
   */
  async addBook(rawNameValues) {
    const nameValues = this._validate('addBook', rawNameValues);
    // console.log('Add Book', nameValues);

    //@TODO
    try {
      const matched = await this.db.collection(COLLECTIONS.BOOK_CATALOG).updateOne(
        {
          isbn: nameValues.isbn
        },
        {
          $set: {
            title: nameValues.title,
            authors: nameValues.authors,
            publisher: nameValues.publisher,
            year: nameValues.year,
            no_of_pages: nameValues.pages,
            _lastModified: new Date().toISOString()
          }
        },
        {
          "upsert": true
        }
      );

      console.log('Match', matched);
    } catch (err) {

    }

  }

  /** Given fields { isbn, authorsTitle, _count=COUNT, _index=0 } =
   *  nameValues, retrieve list of all books with specified isbn (if
   *  any) and the words specified in authorsTitle occurring in either
   *  the book's authors field or the title field.  The retrieved
   *  results are sorted in ascending order by title.  The returned
   *  results have up to _count books starting at index _index in the
   *  retrieved results.  The `_index` and `_count` fields allow
   *  paging through the search results.
   *
   *  Will return [] if no books match the search criteria.
   */
  async findBooks(rawNameValues) {
    try {
      const nameValues = this._validate('findBooks', rawNameValues);
      //@TODO
      console.log('find books', nameValues);

      const cursor = await this.db.collection(COLLECTIONS.BOOK_CATALOG).find(
        {isbn: nameValues.isbn,
          $or: [

            { title: new RegExp('\\b' + nameValues.authorsTitle + '\\b') },
            { authors: [`${nameValues.authorsTitle}`] },
          ],
          
        },,
        {
          limit: Number(COUNT || nameValues._count),
          min: 0 || nameValues._index
        }
       
      ).toArray();
      return cursor || [];
    } catch (err) {

    }
  }

  //wrapper around this.validator to verify that no external field
  //is _id which is used by mongo
  _validate(action, rawNameValues) {
    let errs = [];
    let nameValues;
    try {
      nameValues = this.validator.validate(action, rawNameValues);
    }
    catch (err) {
      if (err instanceof Array) { //something we understand
        errs = err;
      }
      else {
        throw err; //not expected, throw upstairs
      }
    }
    if (rawNameValues._id !== undefined) {
      errs.push(new ModelError('BAD_FIELD', '_id field not permitted', '_id'));
    }
    if (errs.length > 0) throw errs;
    return nameValues;
  }


};

//use as second argument to mongo.connect()
const MONGO_CONNECT_OPTIONS = { useUnifiedTopology: true };

//default value for _count in findBooks()
const COUNT = 5;

//define private constants and functions here.
const DB_NAME = 'books';
let randomCounter = 0;
const COLLECTIONS = {
  SHOPPING_CART: "shopping_cart",
  BOOK_CATALOG: "book_catalog"
}

const SHOPPING_FIELD = {
  CART_ID: "cartId",
  SKU: 'sku',
  NUNITS: 'nUnits'
}

const BOOK_FIELD = {
  ISBN: 'isbn',
  TITLE: 'title',
  AUTHORS: 'authors',
  PUBLISHER: 'publisher',
  YEAR_PUBLISHED: 'year_published',
  PAGES: 'no_of_pages'
}